### ISSUE TITLE
Curvature Flow question

### ISSUE THREAD

**Issue by cjsb** [benma/pysph#2]
Hi,

in the curvature_flow.cl there is two variable w and h and their values are equals to position [0,0]  and [1,1] in the projection matrix. But can you tell me exactly what they express? Is the focal length or (right - left) and (top - bottom) of the camera or something like that? 

best regards,
Caio

**Comment by benma** [comment]
Hi

Here is how the projection matrix is defined (it is a perspective projection):
https://github.com/benma/pysph/blob/master/src/base_demo.py#L58

For the meaning of `fov_y` etc., see for example:
https://www.opengl.org/sdk/docs/man2/xhtml/gluPerspective.xml
https://unspecified.wordpress.com/2012/06/21/calculating-the-gluperspective-matrix-and-other-opengl-matrix-maths/

The latter also goes into detail on how the projection works exactly. The goal is to project an eye-space vector (x,y,z) to screenspace, which ranges from x=[-1...1] and y=[-1...1], if I am not mistaken. It has been a long time ;)

**Comment by cjsb** [comment]
Great,

thanks for the explanation =)

**Comment by cjsb** [comment]
And may I ask how do you get the thickness of the fluid?

**Comment by benma** [comment]
Like this:
https://github.com/benma/pysph/blob/master/src/fluid_rendering/fluid_renderer.py#L201

Also see Simon Green's paper referenced in the README.

**Comment by cjsb** [comment]
Thank you so much!!!

**Comment by cjsb** [comment]
Hi Benma,

can you explain how do you calculate the new normal (after smoothing the surface)?

**Comment by benma** [comment]
https://github.com/benma/pysph/blob/18347a8d3d24eabf60f8fdaac30a44368f1f0ab2/src/fluid_rendering/shader.cg#L154
